[package]
name = "nqueens"
version = "0.1.0"
authors = ["TrAyZeN <1810leo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
clap = "3.0.0-beta.2"

